app:
  name: catalog-service
  page-size: 10

server:
  port: 8081
  shutdown: graceful

spring:
  # db config
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/catalog-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  # jpa and hibernate config
  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"

# Logging for AOT repository generation (useful to see what's being generated)
logging:
  level:
    org:
      springframework:
        data:
          repository:
            aot:
              generate:
                RepositoryContributor: trace