### Order Service Configuration ###
app:
  name: order-service
  catalog-service-base-url: http://localhost:8081
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders
  publish-order-events-job-cron: "*/5 * * * * *"  # it means every 5 seconds
  new-orders-job-cron: "*/10 * * * * *"

server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: order-service
  ### Database Configuration ###
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    show-sql: true
  ### RabbitMQ Configuration ###
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jackson:
    serialization:
      indent-output: true

### Actuator Configuration ###
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1

### Resilience4j config Config ###
resilience4j:
  retry:
    backends:
      catalog-service:
        maxRetryAttempts: 2
        waitDuration: 1s
  circuitbreaker:
    backends:
      catalog-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 6
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50

### Swagger Config ###

### OAuth2 Config ###

