name: catalog-service

on:
  push:
    paths:
      - 'catalog-service/**'
    branches:
      - '**'
env:
  JAVA_VERSION: 25
  working-directory: ./catalog-service

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Set up OpenJDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify --file pom.xml
