name: order-service

on:
  push:
    paths:
      - 'order-service/**'
    branches:
      - '**'
env:
  JAVA_VERSION: 25
  working-directory: ./catalog-service

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ${{env.working-directory}}
      DOCKER_IMAGE: ${{secrets.DOCKER_USERNAME}}/bookstore-order-service
    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Set up OpenJDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          ./mvnw spring-boot:build-image -DskipTests 
          echo "Pushing Docker image $$DOCKER_IMAGE to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME